#!/usr/bin/env bash
#
# Generates local godoc HTML documentation into godocs/.
# Not part of the production build (see build.sh) — pkg.go.dev indexes the
# public module automatically, so this is only useful for offline/local
# browsing. Requires the godoc binary:
#   go install golang.org/x/tools/cmd/godoc@latest
#
set -e
set -o pipefail

printf 'Generating godoc HTML documentation.\n'
GODOC_BIN="$(go env GOPATH)/bin/godoc"
if [ ! -x "$GODOC_BIN" ]; then
    printf 'Error: godoc not found at %s.\n' "$GODOC_BIN"
    printf 'Install with: go install golang.org/x/tools/cmd/godoc@latest\n'
    exit 1
fi

mkdir -p godocs
MODULE="github.com/johndotmcgann/doppler-backup"
GODOC_PORT=6162

# Start godoc server in background
"$GODOC_BIN" -http=":${GODOC_PORT}" &
GODOC_PID=$!

# Wait until godoc is ready (up to 15 seconds)
printf 'Waiting for godoc server to be ready...\n'
RETRIES=0
until wget -q --spider "http://localhost:${GODOC_PORT}/pkg/${MODULE}/" 2>/dev/null; do
    RETRIES=$((RETRIES + 1))
    if [ "$RETRIES" -ge 15 ]; then
        printf 'Error: godoc server did not become ready after 15 seconds.\n'
        kill "$GODOC_PID" 2>/dev/null
        exit 1
    fi
    sleep 1
done

# Mirror the module's package documentation to godocs/
# Internal packages are not linked from the top-level page, so we use
# go list to enumerate every package URL and feed them all to wget.
PACKAGE_URLS=$(go list ./... | sed "s|.*|http://localhost:${GODOC_PORT}/pkg/&/|")
# shellcheck disable=SC2086
wget --recursive \
     --no-parent \
     --page-requisites \
     --convert-links \
     --adjust-extension \
     --no-verbose \
     --no-host-directories \
     --no-clobber \
     --directory-prefix=godocs \
     --include-directories="/pkg/${MODULE},/lib/godoc,/src/${MODULE}" \
     $PACKAGE_URLS

# Stop the godoc server
kill "$GODOC_PID" 2>/dev/null
wait "$GODOC_PID" 2>/dev/null || true

# Generate a custom index.html that links to every package page
printf 'Generating godocs/index.html\n'
INDEX_FILE="godocs/index.html"
cat > "$INDEX_FILE" << HTMLEOF
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>doppler-backup &mdash; Package Documentation</title>
  <link rel="stylesheet" href="lib/godoc/style.css">
  <style>
    body { padding: 1em 2em; font-family: sans-serif; }
    h1   { border-bottom: 1px solid #ccc; padding-bottom: 0.3em; }
    ul   { list-style: none; padding: 0; }
    li   { margin: 0.3em 0; }
    a    { text-decoration: none; color: #375EAB; }
    a:hover { text-decoration: underline; }
    .section { margin-top: 1.5em; }
    .section h2 { font-size: 1.1em; color: #555; margin-bottom: 0.4em; }
  </style>
</head>
<body>
  <h1>doppler-backup &mdash; Package Documentation</h1>
  <p>Generated by <code>godoc</code>. Click a package to view its documentation.</p>
HTMLEOF

# Group packages: root vs internal
ROOT_PKGS=$(go list ./... | grep -v "/internal/")
INTERNAL_PKGS=$(go list ./... | grep "/internal/" || true)

if [ -n "$ROOT_PKGS" ]; then
    printf '  <div class="section"><h2>Root packages</h2><ul>\n' >> "$INDEX_FILE"
    for PKG in $ROOT_PKGS; do
        LABEL=$(echo "$PKG" | sed "s|${MODULE}/||;s|${MODULE}|main|")
        HREF="pkg/${PKG}/index.html"
        printf '    <li><a href="%s">%s</a></li>\n' "$HREF" "$LABEL" >> "$INDEX_FILE"
    done
    printf '  </ul></div>\n' >> "$INDEX_FILE"
fi

if [ -n "$INTERNAL_PKGS" ]; then
    printf '  <div class="section"><h2>Internal packages</h2><ul>\n' >> "$INDEX_FILE"
    for PKG in $INTERNAL_PKGS; do
        LABEL=$(echo "$PKG" | sed "s|${MODULE}/||")
        HREF="pkg/${PKG}/index.html"
        printf '    <li><a href="%s">%s</a></li>\n' "$HREF" "$LABEL" >> "$INDEX_FILE"
    done
    printf '  </ul></div>\n' >> "$INDEX_FILE"
fi

cat >> "$INDEX_FILE" << HTMLEOF
</body>
</html>
HTMLEOF

printf 'Documentation written to godocs/\n'
